package com.miaosha.dao;

import com.miaosha.dataobject.StockLogDO;
import com.miaosha.dataobject.StockLogDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    long countByExample(StockLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    int deleteByExample(StockLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    int insert(StockLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    int insertSelective(StockLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    List<StockLogDO> selectByExample(StockLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    StockLogDO selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") StockLogDO record, @Param("example") StockLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    int updateByExample(@Param("record") StockLogDO record, @Param("example") StockLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    int updateByPrimaryKeySelective(StockLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Nov 15 17:10:10 CST 2019
     */
    int updateByPrimaryKey(StockLogDO record);
}